### PR TITLE
A whole lot a hooey

### PR DESCRIPTION
**Pull request by Rusty-UX**
Here's a bunch of nasty shit.

### CODE REVIEW

**Comment by sunmockyang** [comment]
This works, but lets look into having a single html file instead, and using ruby to replace the `<link rel="stylesheet" href="style/style.css" type="text/css"/>` with the css code

**Comment by sunmockyang** [comment]
+1 go ahead and merge whenever

**Comment by sunmockyang** [comment]
btw, what's script.js? Is it the old code?

**Comment by Rusty-UX** [comment]
Might hold off until we do another code night, good points about substituting the link with the actual css.

**Pull request merged**
